services:
  wireguard:
    build:
      context: ./container-modules/docker-wireguard/
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      wireguard_net:
        ipv4_address: 10.10.0.10
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    volumes:
      - ./volumes/wireguard/config:/config
    ports:
      - 0.0.0.0:51820:51820/udp # WireGuard VPN öffentlich
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    expose:
      - "51820" # Wireguard Service Port

networks:
  wireguard_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
 
