plugins {
    id 'java'
}

group = 'org.wireguard.container'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.13.2'
}

jar {
    archiveFileName = 'wireguard-launcher.jar'
    duplicatesStrategy = 'exclude'
    manifest {
        attributes 'Main-Class': 'org.wireguard.container.WireGuardLauncher'
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
